import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <header>
          <nav>
              <ul className="flex space-x-2">
                  <li>
                      <Link href="/">Home</Link>
                  </li>
                  <li>
                      <Link href="/about">About</Link>
                  </li>
                  <li>
                      <Link href="/profile">Profile</Link>
                  </li>
                  <li>
                      <Link href="/products">Products</Link>
                  </li>
              </ul>
          </nav>

      </header>
      <main className="flex min-h-screen flex-col items-center justify-between p-24">
          {children}
      </main>
      <footer>footer</footer>
      </body>
    </html>
  );
}
